# make UTF-8 encoding explicit
1s/<?xml version="1.0"?>/<?xml version="1.0" encoding="UTF-8"?>/

# add entities for namespaces
# to be kept in sync with the _usage_ of these entities below
1a\
<!DOCTYPE rdf:RDF [\
<!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >\
<!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >\
<!ENTITY owl "http://www.w3.org/2002/07/owl#" >\
<!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >\
<!ENTITY dol "http://www.omg.org/spec/DOL/dol-language/" >\
<!ENTITY dct "http://purl.org/dc/terms/" >\
<!ENTITY skos "http://www.w3.org/2004/02/skos/core#" >\
<!ENTITY sm "http://www.omg.org/techprocess/ab/SpecificationMetadata/" >\
]>

# delete default XML namespace
0,/xmlns="[^"]*"/ {s///;}

# rename some namespace prefixes
0,/xmlns:SpecificationMetadata=/ {s//xmlns:sm=/}
s@\(</\?\)SpecificationMetadata:@\1sm:@g
0,/xmlns:dol-language=/ {s/\(xmlns:dol\)-language\(=\)/\1\2/}
0,/xmlns:terms=/ {s//xmlns:dct=/}
s@\(</\?\)terms:@\1dct:@g

# rewrite full IRIs into &prefix;localname using XML entities as defined above
# to be kept in sync with the definitions above
/<owl:Ontology /,$ {
  s@http://www.w3.org/2000/01/rdf-schema#@\&rdfs;@g
  s@http://www.w3.org/2002/07/owl#@\&owl;@g
  s@http://www.w3.org/2001/XMLSchema#@\&xsd;@g
  s@http://www.omg.org/spec/DOL/dol-language/@\&dol;@g
  s@http://purl.org/dc/terms/@\&dct;@g
  s@http://www.w3.org/2004/02/skos/core#@\&skos;@g
  s@http://www.omg.org/techprocess/ab/SpecificationMetadata/@\&sm;@g
}

# removing OWL API comment
/<!-- Generated by the OWL API /,${//d;}
